### ISSUE TITLE
Some bugs I found

### ISSUE THREAD

**Issue by Kaizuto** [Anreol/ReleasedFromTheVoid#2]
1. The Void Eradicator/Suppressor is named Newt Altar
[image](https://user-images.githubusercontent.com/83712471/159599605-86acf5f1-5488-4718-b8ba-31e3630b7ef7.png)

2. Can't seem to get Major Construct again but when I got it, it is named like a file, something like "boss_enemy_major_construct"

3. Commando skin bugged with Royal Capacitor and Goat Hoof, will completely remove arms/legs until it is scraped/changed and then go into a teleporter/portal

Edit:
4. Theres another bug where coins are not dropping (including from void stalks), on the recent r2api(?) update

**Comment by Anreol** [comment]
The first one is intentional, and that's how Hopoo has it in the game's files, it's like a fake Newt Altar and its name at first reflects it so. Its name and the interaction prompt are similar, but not equal, to a normal newt altar.
For the major construct, since everytime while testing the mod I didn't get it to spawn as a boss, I was actually unaware if it had tokens or not. I can add them for the next update.
And for the commando skin bug, the skin was left unused / unfinished in the game's files, its 100% mirrored, meaning that any item that removes limbs like goat hoofs or the royal capacitor, it will also remove the opposing side's limb. I cannot do anything about this.

I'll check the fourth one, it should totally work, I'll test it now with the latest r2api update

**Comment by Anreol** [comment]
Tested the mod with the latest r2api version, void coins are dropping just fine from the stalks.

**Comment by Kaizuto** [comment]
Found one more bug
![image](https://user-images.githubusercontent.com/83712471/159862877-f0f59248-ac15-4538-8a4c-0043b799500d.png)
the Void Eradicator/Suppressor sometimes flicker when looking at a certain angle

**Comment by Anreol** [comment]
Tried to fix it, but I have absolutely no idea and my changes didn't end up doing anything.
Seems to be a issue with the model itself, so I'm closing this issue as I can't do much about it.
